"""add phone number

Revision ID: 7d3d5cba0b7b
Revises: 8252c30f0b2c
Create Date: 2023-08-23 14:29:47.995892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3d5cba0b7b'
down_revision: Union[str, None] = '8252c30f0b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phonenumber', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phonenumber')
    # ### end Alembic commands ###
